Update Box86-Box64

diff --git a/Box86-Box64 b/Box86-Box64
--- a/Box86-Box64
+++ b/Box86-Box64
@@ -29,5 +29,29 @@ rm -rf box64
 wget https://github.com/ptitSeb/box64/archive/refs/tags/v0.2.2.tar.gz
 wget https://github.com/ptitSeb/box86/archive/refs/tags/v0.3.0.tar.gz
 
+# box86
 
+DEBVER="$(./box86 -v | cut -c21-25)"
 
+  mkdir doc-pak || error "Failed to create doc-pak dir."
+  cp ../docs/README.md ./doc-pak || warning "Failed to add README to docs"
+  cp ../docs/CHANGELOG.md ./doc-pak || error "Failed to add CHANGELOG to docs"
+  cp ../docs/USAGE.md ./doc-pak || error "Failed to add USAGE to docs"
+  cp ../docs/X86WINE.md ./doc-pak || error "Failed to add X86WINE to docs"
+  cp ../LICENSE ./doc-pak || error "Failed to add LICENSE to docs"
+  echo "Box86 lets you run x86 Linux programs (such as games) on non-x86 Linux systems, like ARM (host system needs to be 32bit little-endian)">description-pak || error "Failed to create description-pak."
+  
+sudo checkinstall -y -D --pkgversion="$DEBVER" --arch="armhf" --provides="box86" --conflicts="qemu-user-static" --pkgname="box86" --install="no" make install || error "Checkinstall failed to create a deb package."
+
+# box64 
+ 
+DEBVER="$(./box64 -v | cut -c21-25)"
+
+  mkdir doc-pak || error "Failed to create doc-pak dir."
+  cp ../docs/README.md ./doc-pak || warning "Failed to add readme to docs"
+  cp ../docs/CHANGELOG.md ./doc-pak || error "Failed to add changelog to docs"
+  cp ../docs/USAGE.md ./doc-pak || error "Failed to add USAGE to docs"
+  cp ../LICENSE ./doc-pak || error "Failed to add license to docs"
+  echo "Box64 lets you run x86_64 Linux programs (such as games) on non-x86_64 Linux systems, like ARM (host system needs to be 64bit little-endian)">description-pak || error "Failed to create description-pak."
+ 
+sudo checkinstall -y -D --pkgversion="$DEBVER" --arch="arm64" --provides="box64" --conflicts="qemu-user-static" --pkgname="box64" --install="no" make install || error "Checkinstall failed to create a deb package."
