Update Box86-Box64

diff --git a/Packages/Box86-Box64 b/Packages/Box86-Box64
--- a/Packages/Box86-Box64
+++ b/Packages/Box86-Box64
@@ -42,7 +42,7 @@ cp ../docs/README.md ./doc-pak || warning "Failed to add README to docs"
 cp ../docs/CHANGELOG.md ./doc-pak || error "Failed to add CHANGELOG to docs"
 cp ../docs/USAGE.md ./doc-pak || error "Failed to add USAGE to docs"
 cp ../LICENSE ./doc-pak || error "Failed to add LICENSE to docs"
-echo "Box86 lets you run x86 Linux programs (such as games) on non-x86 Linux systems, like ARM (host system needs to be 32bit little-endian)">description-pak || error "Failed to create description-pak."
+echo "Box86 lets you run x86 Linux programs (such as games) on non-x86_32 Linux systems, like ARM (host system needs to be 32bit little-endian)">description-pak || error "Failed to create description-pak."
 sudo checkinstall -y -D --pkgversion="$DEBVER" --arch="armhf" --provides="box86" --conflicts="box86*" --pkgname="box86-android" --install="no" make install || error "Checkinstall failed to create a deb package."
 
 
